### ISSUE TITLE
[Critical Bug] Missing colon

### ISSUE THREAD

**Issue by shahiro770** [swifteddy/bam2consensus#1]
Missing colon in README makes instructions unclear. Not sure if this is really a disclaimer or a typo.

<div align="center">
  <img src="https://user-images.githubusercontent.com/6191327/235501672-e46d6910-6446-47ce-a784-921bf8f8287b.png" width="664" alt="There is no consensus">
  <p><em>Clearly, there is no CONSENSUS on if this is a disclaimer or if its meant 2 just BAMboozle the user</em></p>
</div>

**Comment by shahiro770** [comment]
Can I get an update please? I'm using this in my project and not sure if there are actually any risks associated with this software.

**Comment by swifteddy** [comment]
I have fixed the issue. *tips hat*
